### ISSUE TITLE
经常提示 QQ 已停止运行，但 QQ 正常

### ISSUE THREAD

**Issue by Menci** [zpp0196/QQPurify#11]
使用过程中经常出现「QQ 已停止运行」的对话框，但点击对话框外区域或关闭程序按钮后对话框消失，QQ 仍可继续正常使用。

因为 QQ 的 `adb logcat` 输出的日志太多了，而且这个错误随机发生，有时候几个小时不发生错误。所以我暂时没有得到有用的错误信息。

**Comment by zpp0196** [comment]
你加一下群  这几天我会放一个测试版你试试

**Comment by Menci** [comment]
发送加群请求了，同头像

**Comment by Menci** [comment]
Android 9.0 用太极没有这个问题了，所以似乎是框架的问题。
