### ISSUE TITLE
新动态界面

### ISSUE THREAD

**Issue by XnzkiONA** [zpp0196/QQPurify#13]
在某天莫名其妙热更新成了这样，小视频和兴趣部落还有聊天框屏蔽不了
![screenshot_2018-09-09-11-56-57-003_com tencent mobileqq](https://user-images.githubusercontent.com/36663185/45260962-d7ad8e80-b427-11e8-8a74-77f09eb3cb18.png)

**Comment by zpp0196** [comment]
跑路了不搞了
