### ISSUE TITLE
QQ7.9.0使用本模块2.7.0会不能自动刷新消息界面

### ISSUE THREAD

**Issue by SennatSu** [zpp0196/QQPurify#18]
如题，手机是一加3T，系统氧OS Beta30（安卓8.0.0），QQ7.9.0.3820使用本模块2.6.0或者2.7.0，无法自动刷新消息列表里的消息，需要手工切桌面，或者点击下面联系人界面，再切回来，才能看到消息列表刷新，卸载本模块恢复正常，希望能修复，万分感谢！

**Comment by ms0ng** [comment]
这个插件已经不再更新了。想用就换回旧版QQ吧

**Comment by SennatSu** [comment]
好的谢谢
