### ISSUE TITLE
聊天界面头像无法正常显示

### ISSUE THREAD

**Issue by singleNeuron** [zpp0196/QQPurify#23]
![screenshot_20190216-033354](https://user-images.githubusercontent.com/23723294/52880229-5ad3cd00-319c-11e9-8e6d-c60df175cc8d.png)

最新版本QQ和插件，edxp2.9

![screenshot_20190216-034311](https://user-images.githubusercontent.com/23723294/52880466-04b35980-319d-11e9-94ec-e04d1ed4e51f.png)

**Comment by zpp0196** [comment]
edxp的锅
