### ISSUE TITLE
一个小提议

### ISSUE THREAD

**Issue by Hidarihitomi** [zpp0196/QQPurify#24]
如果可以的话，聊天界面工具栏隐藏可以保留gif和戳一戳去除么…应该有部分人像我一样用play版没用国内版。目前在用2.7…

**Comment by zpp0196** [comment]
能不能组织好你的语言  我有点懵

**Comment by Hidarihitomi** [comment]
就是play版QQ，聊天界面工具栏还有gif和戳一戳图标，但是净化3.0和3.4版本都没有去除这个了…国内版QQ是已经没有这两个了

**Comment by naloder** [comment]
就是要支持play版吗。。。

**Comment by zpp0196** [comment]
> 就是play版QQ，聊天界面工具栏还有gif和戳一戳图标，但是净化3.0和3.4版本都没有去除这个了…国内版QQ是已经没有这两个了

吃力不讨好的事，没有必要在旧版上浪费时间，2.7和3.4应该不冲突，你可以试试同时使用这两个版本

**Comment by Hidarihitomi** [comment]
> > 就是play版QQ，聊天界面工具栏还有gif和戳一戳图标，但是净化3.0和3.4版本都没有去除这个了…国内版QQ是已经没有这两个了
> 
> 吃力不讨好的事，没有必要在旧版上浪费时间，2.7和3.4应该不冲突，你可以试试同时使用这两个版本

好的…谢谢回复
