### ISSUE TITLE
3.4版在edxp上运行会导致qq主界面列表头像频闪，聊天图片文件无法点击

### ISSUE THREAD

**Issue by weisyr** [zpp0196/QQPurify#28]
EdXposed Installer 2.0
edxp框架版本：0.2.9.9b2
Riru版本：14
(其它版本edxp启用qq净化也是一样的问题)
手机型号：三星S9+ (Pie)

希望大佬能够解决

**Comment by zpp0196** [comment]
edxp的锅我不背
