### ISSUE TITLE
跪求增加净化/隐藏好友功能！！！

### ISSUE THREAD

**Issue by hkcnjd** [zpp0196/QQPurify#29]
既然是净化/隐藏一些多余功能，那么可否隐藏好友呢？
就像WX插件里面的高级功能一样，以及微信巫师的隐藏好友功能，可以手动选择需要隐藏的好友或者群聊。
隐藏后好友或者群聊将会在消息界面、联系人界面以及QQ空间界面消失。以及在搜索界面也无法搜索到。（搜索结果为空）
当隐藏的好友或者群聊发来消息的时候，不会有任何的显示或者提示。以及好友发布QQ空间动态也看不到。 就像没有加这个好友/群聊一样。

当然也可以自定义隐藏好友/群聊来消息的声音选择或者静音或者震动，显示好友/群聊可以在搜索框输入设定好的密码后显示。 

输入密码解锁隐藏好友后可在返回桌面或者锁屏手机的时候自动重新隐藏好友/群聊。

最后感谢作者的辛苦付出，虽然不知您是否会新增这样一个功能，但依然还是非常感谢你了。
愿您快乐。

**Comment by zpp0196** [comment]
此功能过于强大，暂时满足不了你的需求
