### ISSUE TITLE
在QQ 7.9.8上全部失效

### ISSUE THREAD

**Issue by CCRcmcpe** [zpp0196/QQPurify#32]
如题，使用的是太极+miui

**Comment by PianCat** [comment]
@CCRcmcpe 太极是太极阳还是太极阴？
系统版本是安卓几？
QQPurify版本是否为太极支援版本？

**Comment by CCRcmcpe** [comment]
@PianCat
太极阳，android8，是

**Comment by CCRcmcpe** [comment]
经过仔细排查，这可能不是模块自身的问题。希望可以close这个issue。

**Comment by zpp0196** [comment]
说的你就不能close是的😒
