### ISSUE TITLE
4.5.0版本,隐藏字体特效功能存在bug

### ISSUE THREAD

**Issue by Surgeol** [zpp0196/QQPurify#67]
![Screenshot_20190610_092245](https://user-images.githubusercontent.com/35412032/59166982-63904a80-8b61-11e9-8227-dc1760ca5b73.jpg)
当使用 随机大小 的字体特效时,隐藏字体特效的功能疑似失效.
查看其他人的字体特效时,特意在不同的群里随机查看了20+人,字体特效全为 随机大小(实际则不是)  注:这一点我找了其他人测试,应该为QQ的bug,怀疑隐藏字体特效功能的失效与此有关

QQ版本8.0国内版
华为荣耀10,系统EMUI8.1

**Comment by zpp0196** [comment]
有没有相关日志
