### ISSUE TITLE
希望支持8.1.0

### ISSUE THREAD

**Issue by greenhat616** [zpp0196/QQPurify#74]
首先感谢作者的辛苦开发和付出。
以下是问题：
支持内测中的8.1.0
实测 以图片方式打开表情包，闪照失败

另外希望能够干掉qq 8.0.5之后的长按快捷界面，以及 8.1.0 的那个沙雕截图弹窗

**Comment by greenhat616** [comment]
可惜了，不再维护了。 支持pr嘛

**Comment by zpp0196** [comment]
都不维护了你说呢
