### ISSUE TITLE
无法生效

### ISSUE THREAD

**Issue by xiaomengxinyo** [zpp0196/QQPurify#75]
riru19.4和edxposed4.5.5(sandhook)激活了没显示入口(太极可以)，日志应该是这个我不会提取只看到这日志有模块的名字，
07-17 12:53:51.335  1798  1798 I EdXposed-Bridge: Loading modules from /data/app/me.zpp0196.qqpurify-O7_L1eaURyVGiNpVmEk7Cg==/base.apk

07-17 12:53:51.353  1798  1798 I EdXposed-Bridge:   Loading class me.zpp0196.qqpurify.hook.InitializeHook

**Comment by xiaomengxinyo** [comment]
模块版本是4.8.5，3.5.0以上的都是这样

**Comment by zpp0196** [comment]
你框架的问题
